# Generated by Django 2.2.9 on 2020-01-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('addressLine1', models.CharField(max_length=200)),
                ('addressLine2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
